// Drop collections start
db.Bill.drop();
db.Customer.drop();
db.Employee.drop();
db.Medicine.drop();
db.Orders.drop();
//Drop Collections end

//CUstomer Collection Start
db.Customer.insertMany([
  {
    customerId: 1,
    firstName: "Alice",
    lastName: "Johnson",
    address: {
      street: "789 Oak Ln",
      city: "Raleigh",
      state: "NC",
      zipCode: "27601",
    },
    contactNumber: "555-0303",
  },
  {
    customerId: 2,
    firstName: "Bob",
    lastName: "Williams",
    address: {
      street: "101 Pine Ave",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
    },
    contactNumber: "555-0404",
  },
  {
    customerId: 3,
    firstName: "Eva",
    lastName: "Miller",
    address: {
      street: "222 Birch Rd",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
    },
    contactNumber: "555-0505",
  },
  {
    customerId: 4,
    firstName: "Michael",
    lastName: "Brown",
    address: {
      street: "333 Cedar St",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
    },
    contactNumber: "555-0606",
  },
  {
    customerId: 5,
    firstName: "Olivia",
    lastName: "Jones",
    address: {
      street: "444 Walnut Ave",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
    },
    contactNumber: "555-0707",
  },
  {
    customerId: 6,
    firstName: "William",
    lastName: "Davis",
    address: {
      street: "555 Spruce Blvd",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    contactNumber: "555-0808",
  },
  {
    customerId: 7,
    firstName: "Sophia",
    lastName: "Martinez",
    address: {
      street: "666 Pine Ct",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    contactNumber: "555-0909",
  },
  {
    customerId: 8,
    firstName: "Daniel",
    lastName: "Lopez",
    address: {
      street: "777 Oak Dr",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    contactNumber: "555-1010",
  },
  {
    customerId: 9,
    firstName: "Ava",
    lastName: "Garcia",
    address: {
      street: "888 Maple Ln",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
    },
    contactNumber: "555-1111",
  },
  {
    customerId: 10,
    firstName: "Ethan",
    lastName: "Rodriguez",
    address: {
      street: "999 Elm Rd",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
    contactNumber: "555-1212",
  },
  {
    customerId: 11,
    firstName: "Mia",
    lastName: "Hernandez",
    address: {
      street: "123 Oak St",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
    },
    contactNumber: "555-1313",
  },
  {
    customerId: 12,
    firstName: "James",
    lastName: "Gomez",
    address: {
      street: "456 Birch Ave",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
    },
    contactNumber: "555-1414",
  },
  {
    customerId: 13,
    firstName: "Lily",
    lastName: "Cooper",
    address: {
      street: "789 Cedar Blvd",
      city: "Atlanta",
      state: "GA",
      zipCode: "30301",
    },
    contactNumber: "555-1515",
  },
  {
    customerId: 14,
    firstName: "Christopher",
    lastName: "Perez",
    address: {
      street: "101 Pine Dr",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
    },
    contactNumber: "555-1616",
  },
  {
    customerId: 15,
    firstName: "Emma",
    lastName: "Baker",
    address: {
      street: "202 Walnut Rd",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19101",
    },
    contactNumber: "555-1717",
  },
  {
    customerId: 16,
    firstName: "Logan",
    lastName: "Ward",
    address: {
      street: "303 Pine Ct",
      city: "San Diego",
      state: "CA",
      zipCode: "92101",
    },
    contactNumber: "555-1818",
  },
  {
    customerId: 17,
    firstName: "Zoe",
    lastName: "Fisher",
    address: {
      street: "404 Cedar Dr",
      city: "Detroit",
      state: "MI",
      zipCode: "48201",
    },
    contactNumber: "555-1919",
  },
  {
    customerId: 18,
    firstName: "Jackson",
    lastName: "Chen",
    address: {
      street: "505 Maple Rd",
      city: "Minneapolis",
      state: "MN",
      zipCode: "55401",
    },
    contactNumber: "555-2020",
  },
  {
    customerId: 19,
    firstName: "Evelyn",
    lastName: "Liu",
    address: {
      street: "606 Birch Ln",
      city: "Charlotte",
      state: "NC",
      zipCode: "28201",
    },
    contactNumber: "555-2121",
  },
  {
    customerId: 20,
    firstName: "Aiden",
    lastName: "Wang",
    address: {
      street: "707 Oak Blvd",
      city: "Tampa",
      state: "FL",
      zipCode: "33601",
    },
    contactNumber: "555-2222",
  },
  {
    customerId: 21,
    firstName: "Grace",
    lastName: "Morgan",
    address: {
      street: "808 Elm Dr",
      city: "Columbus",
      state: "OH",
      zipCode: "43201",
    },
    contactNumber: "555-2323",
  },
  {
    customerId: 22,
    firstName: "Lucas",
    lastName: "Lopez",
    address: {
      street: "909 Pine Rd",
      city: "San Antonio",
      state: "TX",
      zipCode: "78201",
    },
    contactNumber: "555-2424",
  },
  {
    customerId: 23,
    firstName: "Stella",
    lastName: "Barnes",
    address: {
      street: "101 Maple St",
      city: "Orlando",
      state: "FL",
      zipCode: "32801",
    },
    contactNumber: "555-2525",
  },
  {
    customerId: 24,
    firstName: "Nathan",
    lastName: "Nguyen",
    address: {
      street: "202 Cedar Ave",
      city: "Las Vegas",
      state: "NV",
      zipCode: "89101",
    },
    contactNumber: "555-2626",
  },
  {
    customerId: 25,
    firstName: "Aria",
    lastName: "Kim",
    address: {
      street: "303 Oak Ln",
      city: "Kansas City",
      state: "MO",
      zipCode: "64101",
    },
    contactNumber: "555-2727",
  },
]);

// Customer Collection End

// Employee Collection Start

db.Employee.insertMany([
  {
    employeeId: 1,
    firstName: "Charlie",
    lastName: "Green",
    address: {
      street: "123 Birch St",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    contactNumber: "555-0505",
    position: "Manager",
  },
  {
    employeeId: 2,
    firstName: "Diana",
    lastName: "Brown",
    address: {
      street: "456 Cedar Ln",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85003",
    },
    contactNumber: "555-0606",
    position: "Pharmacist",
  },
  {
    employeeId: 3,
    firstName: "Ethan",
    lastName: "Black",
    address: {
      street: "789 Willow Way",
      city: "Nashville",
      state: "TN",
      zipCode: "37209",
    },
    contactNumber: "555-0707",
    position: "Cashier",
  },
  {
    employeeId: 4,
    firstName: "Fiona",
    lastName: "Gray",
    address: {
      street: "321 Spruce Ave",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
    contactNumber: "555-0808",
    position: "CPhT",
  },
  {
    employeeId: 5,
    firstName: "George",
    lastName: "Adams",
    address: {
      street: "654 Pine St",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    contactNumber: "555-0909",
    position: "Pharmacist",
  },
  {
    employeeId: 6,
    firstName: "Hannah",
    lastName: "Clark",
    address: {
      street: "987 Oak Blvd",
      city: "Boston",
      state: "MA",
      zipCode: "02101",
    },
    contactNumber: "555-1010",
    position: "Cashier",
  },
  {
    employeeId: 7,
    firstName: "Ian",
    lastName: "Davis",
    address: {
      street: "432 Elm St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
    },
    contactNumber: "555-1111",
    position: "Cashier",
  },
]);

// Employee Collection End

// Medicine Collection Start
db.Medicine.insertMany([
  {
    medicineId: 1,
    name: "Ibuprofen",
    manufacturer: "PharmaCare Ltd",
    price: 12.75,
    stock: 120,
    expDate: new Date("2025-09-30"),
  },
  {
    medicineId: 2,
    name: "Amoxicillin",
    manufacturer: "PharmaCare Ltd",
    price: 15.25,
    stock: 90,
    expDate: new Date("2025-08-20"),
  },
  {
    medicineId: 3,
    name: "Cetirizine",
    manufacturer: "HealthRx Solutions",
    price: 9.99,
    stock: 200,
    expDate: new Date("2025-11-15"),
  },
  {
    medicineId: 4,
    name: "Omeprazole",
    manufacturer: "BioMed Co",
    price: 18.5,
    stock: 80,
    expDate: new Date("2025-07-31"),
  },
  {
    medicineId: 5,
    name: "Simvastatin",
    manufacturer: "BioMed Co",
    price: 22.99,
    stock: 150,
    expDate: new Date("2025-10-10"),
  },
  {
    medicineId: 6,
    name: "Losartan",
    manufacturer: "HealthRx Solutions",
    price: 17.5,
    stock: 100,
    expDate: new Date("2025-12-15"),
  },
  {
    medicineId: 7,
    name: "Metformin",
    manufacturer: "PharmaCare Ltd",
    price: 14.99,
    stock: 180,
    expDate: new Date("2025-09-01"),
  },
  {
    medicineId: 8,
    name: "Prednisone",
    manufacturer: "PharmaWell Solutions",
    price: 25.75,
    stock: 70,
    expDate: new Date("2025-08-05"),
  },
  {
    medicineId: 9,
    name: "Levothyroxine",
    manufacturer: "VitalCure Ltd",
    price: 11.25,
    stock: 120,
    expDate: new Date("2025-10-25"),
  },
  {
    medicineId: 10,
    name: "Diazepam",
    manufacturer: "VitalCure Ltd",
    price: 30.99,
    stock: 50,
    expDate: new Date("2025-07-15"),
  },
  {
    medicineId: 11,
    name: "Naproxen",
    manufacturer: "PharmaCare Ltd",
    price: 14.5,
    stock: 100,
    expDate: new Date("2025-11-30"),
  },
  {
    medicineId: 12,
    name: "Cephalexin",
    manufacturer: "PharmaCare Ltd",
    price: 16.75,
    stock: 120,
    expDate: new Date("2025-10-15"),
  },
  {
    medicineId: 13,
    name: "Loratadine",
    manufacturer: "HealthRx Solutions",
    price: 8.25,
    stock: 180,
    expDate: new Date("2025-12-01"),
  },
  {
    medicineId: 14,
    name: "Pantoprazole",
    manufacturer: "BioMed Co",
    price: 20.99,
    stock: 90,
    expDate: new Date("2025-09-20"),
  },
  {
    medicineId: 15,
    name: "Atorvastatin",
    manufacturer: "BioMed Co",
    price: 24.5,
    stock: 150,
    expDate: new Date("2025-08-10"),
  },
  {
    medicineId: 16,
    name: "Valsartan",
    manufacturer: "HealthRx Solutions",
    price: 18.25,
    stock: 110,
    expDate: new Date("2025-11-25"),
  },
  {
    medicineId: 17,
    name: "Glimepiride",
    manufacturer: "PharmaCare Ltd",
    price: 13.99,
    stock: 200,
    expDate: new Date("2025-09-10"),
  },
  {
    medicineId: 18,
    name: "Methylprednisolone",
    manufacturer: "PharmaWell Solutions",
    price: 27.75,
    stock: 80,
    expDate: new Date("2025-07-05"),
  },
  {
    medicineId: 19,
    name: "Synthroid",
    manufacturer: "VitalCure Ltd",
    price: 10.5,
    stock: 130,
    expDate: new Date("2025-10-20"),
  },
  {
    medicineId: 20,
    name: "Lorazepam",
    manufacturer: "VitalCure Ltd",
    price: 33.25,
    stock: 60,
    expDate: new Date("2025-08-15"),
  },
  {
    medicineId: 21,
    name: "Pantoprazole",
    manufacturer: "BioMed Co",
    price: 20.99,
    stock: 90,
    expDate: new Date("2023-01-20"),
  },
  {
    medicineId: 22,
    name: "Atorvastatin",
    manufacturer: "BioMed Co",
    price: 24.5,
    stock: 150,
    expDate: new Date("2023-01-10"),
  },
  {
    medicineId: 23,
    name: "Valsartan",
    manufacturer: "HealthRx Solutions",
    price: 18.25,
    stock: 110,
    expDate: new Date("2023-01-25"),
  },
  {
    medicineId: 24,
    name: "Glimepiride",
    manufacturer: "PharmaCare Ltd",
    price: 13.99,
    stock: 200,
    expDate: new Date("2023-01-10"),
  },
  {
    medicineId: 25,
    name: "Methylprednisolone",
    manufacturer: "PharmaWell Solutions",
    price: 27.75,
    stock: 80,
    expDate: new Date("2023-01-05"),
  },
  {
    medicineId: 26,
    name: "Synthroid",
    manufacturer: "VitalCure Ltd",
    price: 10.5,
    stock: 130,
    expDate: new Date("2023-01-20"),
  },
  {
    medicineId: 27,
    name: "Lorazepam",
    manufacturer: "VitalCure Ltd",
    price: 33.25,
    stock: 60,
    expDate: new Date("2023-01-15"),
  },
  {
    medicineId: 28,
    name: "Ibuprofen",
    manufacturer: "PharmaCare Ltd",
    price: 12.75,
    stock: 120,
    expDate: new Date("2022-09-30"),
  },
  {
    medicineId: 29,
    name: "Amoxicillin",
    manufacturer: "PharmaCare Ltd",
    price: 15.25,
    stock: 90,
    expDate: new Date("2022-08-20"),
  },
  {
    medicineId: 30,
    name: "Cetirizine",
    manufacturer: "HealthRx Solutions",
    price: 9.99,
    stock: 200,
    expDate: new Date("2022-11-15"),
  },
  {
    medicineId: 31,
    name: "Omeprazole",
    manufacturer: "BioMed Co",
    price: 18.5,
    stock: 80,
    expDate: new Date("2022-07-31"),
  },
  {
    medicineId: 32,
    name: "Simvastatin",
    manufacturer: "BioMed Co",
    price: 22.99,
    stock: 150,
    expDate: new Date("2022-10-10"),
  },
  {
    medicineId: 33,
    name: "Losartan",
    manufacturer: "HealthRx Solutions",
    price: 17.5,
    stock: 100,
    expDate: new Date("2022-12-15"),
  },
  {
    medicineId: 34,
    name: "Metformin",
    manufacturer: "PharmaCare Ltd",
    price: 14.99,
    stock: 180,
    expDate: new Date("2022-09-01"),
  },
  {
    medicineId: 35,
    name: "Prednisone",
    manufacturer: "PharmaWell Solutions",
    price: 25.75,
    stock: 70,
    expDate: new Date("2022-08-05"),
  },
  {
    medicineId: 36,
    name: "Levothyroxine",
    manufacturer: "VitalCure Ltd",
    price: 11.25,
    stock: 120,
    expDate: new Date("2022-10-25"),
  },
  {
    medicineId: 37,
    name: "Diazepam",
    manufacturer: "VitalCure Ltd",
    price: 30.99,
    stock: 50,
    expDate: new Date("2022-07-15"),
  },
]);

//medicine Collection End

//Orders Collection Start
db.Orders.insertMany([
  {
    orderId: 1,
    customerId: 10,
    employeeId: 6,
    orderDate: new Date("2023-01-27"),
    orderDetails: [{ medicineId: 21, quantity: 2 }],
  },
  {
    orderId: 2,
    customerId: 12,
    employeeId: 3,
    orderDate: new Date("2023-02-10"),
    orderDetails: [{ medicineId: 1, quantity: 1 }],
  },
  {
    orderId: 3,
    customerId: 13,
    employeeId: 7,
    orderDate: new Date("2023-01-27"),
    orderDetails: [{ medicineId: 1, quantity: 2 }],
  },
  {
    orderId: 4,
    customerId: 14,
    employeeId: 3,
    orderDate: new Date("2023-02-10"),
    orderDetails: [{ medicineId: 1, quantity: 3 }],
  },
  {
    orderId: 5,
    customerId: 15,
    employeeId: 3,
    orderDate: new Date("2023-02-01"),
    orderDetails: [{ medicineId: 2, quantity: 4 }],
  },
  {
    orderId: 6,
    customerId: 16,
    employeeId: 6,
    orderDate: new Date("2023-02-17"),
    orderDetails: [{ medicineId: 3, quantity: 3 }],
  },
  {
    orderId: 7,
    customerId: 17,
    employeeId: 6,
    orderDate: new Date("2023-02-08"),
    orderDetails: [{ medicineId: 11, quantity: 5 }],
  },
  {
    orderId: 8,
    customerId: 18,
    employeeId: 6,
    orderDate: new Date("2023-02-18"),
    orderDetails: [{ medicineId: 30, quantity: 3 }],
  },
  {
    orderId: 9,
    customerId: 19,
    employeeId: 7,
    orderDate: new Date("2023-02-05"),
    orderDetails: [{ medicineId: 20, quantity: 3 }],
  },
  {
    orderId: 10,
    customerId: 20,
    employeeId: 7,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 21, quantity: 3 }],
  },

  {
    orderId: 11,
    customerId: 1,
    employeeId: 3,
    orderDate: new Date("2023-02-05"),
    orderDetails: [{ medicineId: 22, quantity: 6 }],
  },
  {
    orderId: 12,
    customerId: 2,
    employeeId: 3,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 23, quantity: 3 }],
  },
  {
    orderId: 13,
    customerId: 3,
    employeeId: 6,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 24, quantity: 5 }],
  },
  {
    orderId: 14,
    customerId: 4,
    employeeId: 6,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 25, quantity: 2 }],
  },
  {
    orderId: 15,
    customerId: 4,
    employeeId: 6,
    orderDate: new Date("2023-02-18"),
    orderDetails: [{ medicineId: 26, quantity: 1 }],
  },
  {
    orderId: 16,
    customerId: 5,
    employeeId: 7,
    orderDate: new Date("2023-02-28"),
    orderDetails: [{ medicineId: 27, quantity: 3 }],
  },
  {
    orderId: 17,
    customerId: 6,
    employeeId: 3,
    orderDate: new Date("2023-03-01"),
    orderDetails: [{ medicineId: 28, quantity: 7 }],
  },
  {
    orderId: 18,
    customerId: 7,
    employeeId: 7,
    orderDate: new Date("2023-03-02"),
    orderDetails: [{ medicineId: 32, quantity: 2 }],
  },
  {
    orderId: 19,
    customerId: 8,
    employeeId: 7,
    orderDate: new Date("2023-03-03"),
    orderDetails: [{ medicineId: 33, quantity: 3 }],
  },

  {
    orderId: 20,
    customerId: 1,
    employeeId: 3,
    orderDate: new Date("2023-03-05"),
    orderDetails: [
      { medicineId: 1, quantity: 2 },
      { medicineId: 2, quantity: 1 },
    ],
  },
  {
    orderId: 21,
    customerId: 2,
    employeeId: 6,
    orderDate: new Date("2023-03-10"),
    orderDetails: [
      { medicineId: 2, quantity: 1 },
      { medicineId: 4, quantity: 2 },
    ],
  },
  {
    orderId: 22,
    customerId: 3,
    employeeId: 7,
    orderDate: new Date("2023-03-11"),
    orderDetails: [
      { medicineId: 3, quantity: 1 },
      { medicineId: 4, quantity: 2 },
    ],
  },
  {
    orderId: 23,
    customerId: 4,
    employeeId: 3,
    orderDate: new Date("2023-03-20"),
    orderDetails: [
      { medicineId: 4, quantity: 5 },
      { medicineId: 2, quantity: 2 },
    ],
  },
  {
    orderId: 24,
    customerId: 4,
    employeeId: 6,
    orderDate: new Date("2023-03-23"),
    orderDetails: [
      { medicineId: 5, quantity: 2 },
      { medicineId: 4, quantity: 2 },
    ],
  },

  {
    orderId: 25,
    customerId: 5,
    employeeId: 7,
    orderDate: new Date("2023-03-25"),
    orderDetails: [
      { medicineId: 6, quantity: 3 },
      { medicineId: 4, quantity: 2 },
    ],
  },
  {
    orderId: 26,
    customerId: 6,
    employeeId: 3,
    orderDate: new Date("2023-03-30"),
    orderDetails: [
      { medicineId: 7, quantity: 4 },
      { medicineId: 8, quantity: 2 },
    ],
  },
  {
    orderId: 27,
    customerId: 7,
    employeeId: 6,
    orderDate: new Date("2023-04-01"),
    orderDetails: [
      { medicineId: 9, quantity: 2 },
      { medicineId: 10, quantity: 1 },
    ],
  },
  {
    orderId: 28,
    customerId: 8,
    employeeId: 7,
    orderDate: new Date("2023-04-05"),
    orderDetails: [
      { medicineId: 11, quantity: 3 },
      { medicineId: 12, quantity: 2 },
    ],
  },
  {
    orderId: 29,
    customerId: 9,
    employeeId: 3,
    orderDate: new Date("2023-04-10"),
    orderDetails: [
      { medicineId: 13, quantity: 1 },
      { medicineId: 14, quantity: 2 },
    ],
  },

  {
    orderId: 30,
    customerId: 10,
    employeeId: 6,
    orderDate: new Date("2023-04-15"),
    orderDetails: [
      { medicineId: 15, quantity: 2 },
      { medicineId: 16, quantity: 3 },
    ],
  },
  {
    orderId: 31,
    customerId: 11,
    employeeId: 7,
    orderDate: new Date("2023-04-20"),
    orderDetails: [
      { medicineId: 17, quantity: 2 },
      { medicineId: 18, quantity: 1 },
    ],
  },
  {
    orderId: 32,
    customerId: 12,
    employeeId: 3,
    orderDate: new Date("2023-04-25"),
    orderDetails: [
      { medicineId: 19, quantity: 4 },
      { medicineId: 20, quantity: 2 },
    ],
  },
  {
    orderId: 33,
    customerId: 13,
    employeeId: 6,
    orderDate: new Date("2023-05-01"),
    orderDetails: [
      { medicineId: 21, quantity: 3 },
      { medicineId: 22, quantity: 2 },
    ],
  },
  {
    orderId: 34,
    customerId: 14,
    employeeId: 7,
    orderDate: new Date("2023-05-05"),
    orderDetails: [
      { medicineId: 23, quantity: 2 },
      { medicineId: 24, quantity: 1 },
    ],
  },

  {
    orderId: 35,
    customerId: 15,
    employeeId: 3,
    orderDate: new Date("2023-05-10"),
    orderDetails: [
      { medicineId: 25, quantity: 3 },
      { medicineId: 26, quantity: 2 },
    ],
  },
  {
    orderId: 36,
    customerId: 16,
    employeeId: 6,
    orderDate: new Date("2023-05-15"),
    orderDetails: [
      { medicineId: 27, quantity: 2 },
      { medicineId: 28, quantity: 1 },
    ],
  },
  {
    orderId: 37,
    customerId: 17,
    employeeId: 7,
    orderDate: new Date("2023-05-20"),
    orderDetails: [
      { medicineId: 29, quantity: 4 },
      { medicineId: 30, quantity: 2 },
    ],
  },
  {
    orderId: 38,
    customerId: 18,
    employeeId: 3,
    orderDate: new Date("2023-05-25"),
    orderDetails: [
      { medicineId: 31, quantity: 3 },
      { medicineId: 32, quantity: 2 },
    ],
  },
  {
    orderId: 39,
    customerId: 19,
    employeeId: 6,
    orderDate: new Date("2023-06-01"),
    orderDetails: [
      { medicineId: 33, quantity: 2 },
      { medicineId: 34, quantity: 1 },
    ],
  },
  {
    orderId: 40,
    customerId: 20,
    employeeId: 7,
    orderDate: new Date("2023-06-05"),
    orderDetails: [
      { medicineId: 35, quantity: 3 },
      { medicineId: 36, quantity: 2 },
    ],
  },
  {
    orderId: 41,
    customerId: 1,
    employeeId: 3,
    orderDate: new Date("2023-06-10"),
    orderDetails: [
      { medicineId: 1, quantity: 5 },
      { medicineId: 2, quantity: 2 },
    ],
  },
  {
    orderId: 42,
    customerId: 2,
    employeeId: 6,
    orderDate: new Date("2023-06-15"),
    orderDetails: [
      { medicineId: 3, quantity: 2 },
      { medicineId: 4, quantity: 1 },
    ],
  },
  {
    orderId: 43,
    customerId: 3,
    employeeId: 7,
    orderDate: new Date("2023-06-20"),
    orderDetails: [
      { medicineId: 5, quantity: 4 },
      { medicineId: 6, quantity: 2 },
    ],
  },
  {
    orderId: 44,
    customerId: 4,
    employeeId: 3,
    orderDate: new Date("2023-06-25"),
    orderDetails: [
      { medicineId: 7, quantity: 3 },
      { medicineId: 8, quantity: 2 },
    ],
  },
  {
    orderId: 45,
    customerId: 5,
    employeeId: 6,
    orderDate: new Date("2023-07-01"),
    orderDetails: [
      { medicineId: 9, quantity: 5 },
      { medicineId: 10, quantity: 3 },
    ],
  },
  {
    orderId: 46,
    customerId: 6,
    employeeId: 3,
    orderDate: new Date("2023-07-05"),
    orderDetails: [
      { medicineId: 11, quantity: 4 },
      { medicineId: 12, quantity: 2 },
    ],
  },
  {
    orderId: 47,
    customerId: 7,
    employeeId: 6,
    orderDate: new Date("2023-07-10"),
    orderDetails: [
      { medicineId: 13, quantity: 3 },
      { medicineId: 14, quantity: 1 },
    ],
  },
  {
    orderId: 48,
    customerId: 8,
    employeeId: 7,
    orderDate: new Date("2023-07-15"),
    orderDetails: [
      { medicineId: 15, quantity: 6 },
      { medicineId: 16, quantity: 2 },
    ],
  },
  {
    orderId: 49,
    customerId: 9,
    employeeId: 3,
    orderDate: new Date("2023-07-20"),
    orderDetails: [
      { medicineId: 17, quantity: 2 },
      { medicineId: 18, quantity: 3 },
    ],
  },
  {
    orderId: 50,
    customerId: 10,
    employeeId: 6,
    orderDate: new Date("2023-07-25"),
    orderDetails: [
      { medicineId: 19, quantity: 4 },
      { medicineId: 20, quantity: 5 },
    ],
  },
  {
    orderId: 51,
    customerId: 11,
    employeeId: 7,
    orderDate: new Date("2023-07-30"),
    orderDetails: [
      { medicineId: 21, quantity: 3 },
      { medicineId: 22, quantity: 2 },
    ],
  },
  {
    orderId: 52,
    customerId: 12,
    employeeId: 3,
    orderDate: new Date("2023-08-01"),
    orderDetails: [
      { medicineId: 23, quantity: 5 },
      { medicineId: 24, quantity: 3 },
    ],
  },
  {
    orderId: 53,
    customerId: 13,
    employeeId: 6,
    orderDate: new Date("2023-08-05"),
    orderDetails: [
      { medicineId: 25, quantity: 2 },
      { medicineId: 26, quantity: 4 },
    ],
  },
  {
    orderId: 54,
    customerId: 14,
    employeeId: 7,
    orderDate: new Date("2023-08-10"),
    orderDetails: [
      { medicineId: 27, quantity: 3 },
      { medicineId: 28, quantity: 1 },
    ],
  },
]);
//Orders collection End

//Bill Collection Start
db.Bill.insertMany([
  { billId: 1, orderID: 1, totalAmount: 29, paymentStatus: "Unpaid" },
  { billId: 2, orderID: 2, totalAmount: 12.75, paymentStatus: "Unpaid" },
  { billId: 3, orderID: 3, totalAmount: 25.5, paymentStatus: "Unpaid" },
  { billId: 4, orderID: 4, totalAmount: 38.25, paymentStatus: "Unpaid" },
  { billId: 5, orderID: 5, totalAmount: 61, paymentStatus: "Unpaid" },
  { billId: 6, orderID: 6, totalAmount: 29.97, paymentStatus: "Unpaid" },
  { billId: 7, orderID: 7, totalAmount: 72.5, paymentStatus: "Unpaid" },
  { billId: 8, orderID: 8, totalAmount: 99.75, paymentStatus: "Unpaid" },
  { billId: 9, orderID: 9, totalAmount: 99.75, paymentStatus: "Unpaid" },
  { billId: 11, orderID: 11, totalAmount: 100.5, paymentStatus: "Paid" },
  { billId: 10, orderID: 10, totalAmount: 43.5, paymentStatus: "Unpaid" },
  { billId: 12, orderID: 12, totalAmount: 24.75, paymentStatus: "Paid" },
  { billId: 13, orderID: 13, totalAmount: 104.95, paymentStatus: "Paid" },
  { billId: 14, orderID: 14, totalAmount: 49, paymentStatus: "Paid" },
  { billId: 15, orderID: 15, totalAmount: 18.25, paymentStatus: "Paid" },
  { billId: 16, orderID: 16, totalAmount: 41.97, paymentStatus: "Paid" },
  { billId: 17, orderID: 17, totalAmount: 194.25, paymentStatus: "Paid" },
  { billId: 18, orderID: 18, totalAmount: 49, paymentStatus: "Paid" },
  { billId: 19, orderID: 19, totalAmount: 54.75, paymentStatus: "Paid" },
  { billId: 20, orderID: 20, totalAmount: 40.75, paymentStatus: "Paid" },
  { billId: 21, orderID: 21, totalAmount: 52.25, paymentStatus: "Paid" },
  { billId: 22, orderID: 22, totalAmount: 46.99, paymentStatus: "Paid" },
  { billId: 23, orderID: 23, totalAmount: 129.5, paymentStatus: "Paid" },
  { billId: 24, orderID: 24, totalAmount: 82.98, paymentStatus: "Paid" },
  { billId: 25, orderID: 25, totalAmount: 159.5, paymentStatus: "Paid" },
  { billId: 26, orderID: 26, totalAmount: 171.91, paymentStatus: "Paid" },
  { billId: 27, orderID: 27, totalAmount: 294.5, paymentStatus: "Paid" },
  { billId: 28, orderID: 28, totalAmount: 59.5, paymentStatus: "Paid" },
  { billId: 29, orderID: 29, totalAmount: 129.97, paymentStatus: "Paid" },
  { billId: 30, orderID: 30, totalAmount: 80.5, paymentStatus: "Paid" },
  { billId: 31, orderID: 31, totalAmount: 104, paymentStatus: "Paid" },
  { billId: 32, orderID: 32, totalAmount: 78.25, paymentStatus: "Paid" },
  { billId: 33, orderID: 33, totalAmount: 162.94, paymentStatus: "Paid" },
  { billId: 34, orderID: 34, totalAmount: 233, paymentStatus: "Paid" },
  { billId: 35, orderID: 35, totalAmount: 110, paymentStatus: "Paid" },
  { billId: 36, orderID: 36, totalAmount: 176.9, paymentStatus: "Paid" },
  { billId: 37, orderID: 37, totalAmount: 124, paymentStatus: "Paid" },
  { billId: 38, orderID: 38, totalAmount: 154.25, paymentStatus: "Paid" },
  { billId: 39, orderID: 39, totalAmount: 259, paymentStatus: "Paid" },
  { billId: 40, orderID: 40, totalAmount: 269.75, paymentStatus: "Paid" },
  { billId: 41, orderID: 41, totalAmount: 73.5, paymentStatus: "Paid" },
  { billId: 42, orderID: 42, totalAmount: 45.25, paymentStatus: "Paid" },
  { billId: 43, orderID: 43, totalAmount: 86.5, paymentStatus: "Paid" },
  { billId: 44, orderID: 44, totalAmount: 82.98, paymentStatus: "Paid" },
  { billId: 45, orderID: 45, totalAmount: 82.98, paymentStatus: "Paid" },
  { billId: 46, orderID: 46, totalAmount: 266.9, paymentStatus: "Paid" },
  { billId: 47, orderID: 47, totalAmount: 470.86, paymentStatus: "Paid" },
  { billId: 48, orderID: 48, totalAmount: 51.5, paymentStatus: "Paid" },
  { billId: 49, orderID: 49, totalAmount: 183.93, paymentStatus: "Paid" },
  { billId: 50, orderID: 50, totalAmount: 103.5, paymentStatus: "Paid" },
  { billId: 51, orderID: 51, totalAmount: 73.5, paymentStatus: "Paid" },
  { billId: 52, orderID: 52, totalAmount: 78.98, paymentStatus: "Paid" },
  { billId: 53, orderID: 53, totalAmount: 88.5, paymentStatus: "Paid" },
  { billId: 54, orderID: 54, totalAmount: 0, paymentStatus: "Paid" },
]);

// Update the order references in each bill document
db.Bill.find({}).forEach(function (bill) {
  db.Bill.update(
    { _id: bill._id },
    { $set: { orderID: db.Orders.findOne({ orderId: bill.orderID })._id } }
  );
});

//BIll collection ENd
