db.Bill.insertMany([
  { billId: 1, orderID: 1, totalAmount: 29, paymentStatus: "Unpaid" },
  { billId: 2, orderID: 2, totalAmount: 12.75, paymentStatus: "Unpaid" },
  { billId: 3, orderID: 3, totalAmount: 25.5, paymentStatus: "Unpaid" },
  { billId: 4, orderID: 4, totalAmount: 38.25, paymentStatus: "Unpaid" },
  { billId: 5, orderID: 5, totalAmount: 61, paymentStatus: "Unpaid" },
  { billId: 6, orderID: 6, totalAmount: 29.97, paymentStatus: "Unpaid" },
  { billId: 7, orderID: 7, totalAmount: 72.5, paymentStatus: "Unpaid" },
  { billId: 8, orderID: 8, totalAmount: 99.75, paymentStatus: "Unpaid" },
  { billId: 9, orderID: 9, totalAmount: 99.75, paymentStatus: "Unpaid" },
  { billId: 11, orderID: 11, totalAmount: 100.5, paymentStatus: "Paid" },
  { billId: 10, orderID: 10, totalAmount: 43.5, paymentStatus: "Unpaid" },
  { billId: 12, orderID: 12, totalAmount: 24.75, paymentStatus: "Paid" },
  { billId: 13, orderID: 13, totalAmount: 104.95, paymentStatus: "Paid" },
  { billId: 14, orderID: 14, totalAmount: 49, paymentStatus: "Paid" },
  { billId: 15, orderID: 15, totalAmount: 18.25, paymentStatus: "Paid" },
  { billId: 16, orderID: 16, totalAmount: 41.97, paymentStatus: "Paid" },
  { billId: 17, orderID: 17, totalAmount: 194.25, paymentStatus: "Paid" },
  { billId: 18, orderID: 18, totalAmount: 49, paymentStatus: "Paid" },
  { billId: 19, orderID: 19, totalAmount: 54.75, paymentStatus: "Paid" },
  { billId: 20, orderID: 20, totalAmount: 40.75, paymentStatus: "Paid" },
  { billId: 21, orderID: 21, totalAmount: 52.25, paymentStatus: "Paid" },
  { billId: 22, orderID: 22, totalAmount: 46.99, paymentStatus: "Paid" },
  { billId: 23, orderID: 23, totalAmount: 129.5, paymentStatus: "Paid" },
  { billId: 24, orderID: 24, totalAmount: 82.98, paymentStatus: "Paid" },
  { billId: 25, orderID: 25, totalAmount: 159.5, paymentStatus: "Paid" },
  { billId: 26, orderID: 26, totalAmount: 171.91, paymentStatus: "Paid" },
  { billId: 27, orderID: 27, totalAmount: 294.5, paymentStatus: "Paid" },
  { billId: 28, orderID: 28, totalAmount: 59.5, paymentStatus: "Paid" },
  { billId: 29, orderID: 29, totalAmount: 129.97, paymentStatus: "Paid" },
  { billId: 30, orderID: 30, totalAmount: 80.5, paymentStatus: "Paid" },
  { billId: 31, orderID: 31, totalAmount: 104, paymentStatus: "Paid" },
  { billId: 32, orderID: 32, totalAmount: 78.25, paymentStatus: "Paid" },
  { billId: 33, orderID: 33, totalAmount: 162.94, paymentStatus: "Paid" },
  { billId: 34, orderID: 34, totalAmount: 233, paymentStatus: "Paid" },
  { billId: 35, orderID: 35, totalAmount: 110, paymentStatus: "Paid" },
  { billId: 36, orderID: 36, totalAmount: 176.9, paymentStatus: "Paid" },
  { billId: 37, orderID: 37, totalAmount: 124, paymentStatus: "Paid" },
  { billId: 38, orderID: 38, totalAmount: 154.25, paymentStatus: "Paid" },
  { billId: 39, orderID: 39, totalAmount: 259, paymentStatus: "Paid" },
  { billId: 40, orderID: 40, totalAmount: 269.75, paymentStatus: "Paid" },
  { billId: 41, orderID: 41, totalAmount: 73.5, paymentStatus: "Paid" },
  { billId: 42, orderID: 42, totalAmount: 45.25, paymentStatus: "Paid" },
  { billId: 43, orderID: 43, totalAmount: 86.5, paymentStatus: "Paid" },
  { billId: 44, orderID: 44, totalAmount: 82.98, paymentStatus: "Paid" },
  { billId: 45, orderID: 45, totalAmount: 82.98, paymentStatus: "Paid" },
  { billId: 46, orderID: 46, totalAmount: 266.9, paymentStatus: "Paid" },
  { billId: 47, orderID: 47, totalAmount: 470.86, paymentStatus: "Paid" },
  { billId: 48, orderID: 48, totalAmount: 51.5, paymentStatus: "Paid" },
  { billId: 49, orderID: 49, totalAmount: 183.93, paymentStatus: "Paid" },
  { billId: 50, orderID: 50, totalAmount: 103.5, paymentStatus: "Paid" },
  { billId: 51, orderID: 51, totalAmount: 73.5, paymentStatus: "Paid" },
  { billId: 52, orderID: 52, totalAmount: 78.98, paymentStatus: "Paid" },
  { billId: 53, orderID: 53, totalAmount: 88.5, paymentStatus: "Paid" },
  { billId: 54, orderID: 54, totalAmount: 0, paymentStatus: "Paid" },
]);

// Update the order references in each bill document
db.Bill.find({}).forEach(function (bill) {
  db.Bill.update(
    { _id: bill._id },
    { $set: { orderID: db.Orders.findOne({ orderId: bill.orderID })._id } }
  );
});
