db.Customer.insertMany([
  {
    customerId: 1,
    firstName: "Alice",
    lastName: "Johnson",
    address: {
      street: "789 Oak Ln",
      city: "Raleigh",
      state: "NC",
      zipCode: "27601",
    },
    contactNumber: "555-0303",
  },
  {
    customerId: 2,
    firstName: "Bob",
    lastName: "Williams",
    address: {
      street: "101 Pine Ave",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
    },
    contactNumber: "555-0404",
  },
  {
    customerId: 3,
    firstName: "Eva",
    lastName: "Miller",
    address: {
      street: "222 Birch Rd",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
    },
    contactNumber: "555-0505",
  },
  {
    customerId: 4,
    firstName: "Michael",
    lastName: "Brown",
    address: {
      street: "333 Cedar St",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
    },
    contactNumber: "555-0606",
  },
  {
    customerId: 5,
    firstName: "Olivia",
    lastName: "Jones",
    address: {
      street: "444 Walnut Ave",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
    },
    contactNumber: "555-0707",
  },
  {
    customerId: 6,
    firstName: "William",
    lastName: "Davis",
    address: {
      street: "555 Spruce Blvd",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    contactNumber: "555-0808",
  },
  {
    customerId: 7,
    firstName: "Sophia",
    lastName: "Martinez",
    address: {
      street: "666 Pine Ct",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    contactNumber: "555-0909",
  },
  {
    customerId: 8,
    firstName: "Daniel",
    lastName: "Lopez",
    address: {
      street: "777 Oak Dr",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    contactNumber: "555-1010",
  },
  {
    customerId: 9,
    firstName: "Ava",
    lastName: "Garcia",
    address: {
      street: "888 Maple Ln",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
    },
    contactNumber: "555-1111",
  },
  {
    customerId: 10,
    firstName: "Ethan",
    lastName: "Rodriguez",
    address: {
      street: "999 Elm Rd",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
    contactNumber: "555-1212",
  },
  {
    customerId: 11,
    firstName: "Mia",
    lastName: "Hernandez",
    address: {
      street: "123 Oak St",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
    },
    contactNumber: "555-1313",
  },
  {
    customerId: 12,
    firstName: "James",
    lastName: "Gomez",
    address: {
      street: "456 Birch Ave",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
    },
    contactNumber: "555-1414",
  },
  {
    customerId: 13,
    firstName: "Lily",
    lastName: "Cooper",
    address: {
      street: "789 Cedar Blvd",
      city: "Atlanta",
      state: "GA",
      zipCode: "30301",
    },
    contactNumber: "555-1515",
  },
  {
    customerId: 14,
    firstName: "Christopher",
    lastName: "Perez",
    address: {
      street: "101 Pine Dr",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
    },
    contactNumber: "555-1616",
  },
  {
    customerId: 15,
    firstName: "Emma",
    lastName: "Baker",
    address: {
      street: "202 Walnut Rd",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19101",
    },
    contactNumber: "555-1717",
  },
  {
    customerId: 16,
    firstName: "Logan",
    lastName: "Ward",
    address: {
      street: "303 Pine Ct",
      city: "San Diego",
      state: "CA",
      zipCode: "92101",
    },
    contactNumber: "555-1818",
  },
  {
    customerId: 17,
    firstName: "Zoe",
    lastName: "Fisher",
    address: {
      street: "404 Cedar Dr",
      city: "Detroit",
      state: "MI",
      zipCode: "48201",
    },
    contactNumber: "555-1919",
  },
  {
    customerId: 18,
    firstName: "Jackson",
    lastName: "Chen",
    address: {
      street: "505 Maple Rd",
      city: "Minneapolis",
      state: "MN",
      zipCode: "55401",
    },
    contactNumber: "555-2020",
  },
  {
    customerId: 19,
    firstName: "Evelyn",
    lastName: "Liu",
    address: {
      street: "606 Birch Ln",
      city: "Charlotte",
      state: "NC",
      zipCode: "28201",
    },
    contactNumber: "555-2121",
  },
  {
    customerId: 20,
    firstName: "Aiden",
    lastName: "Wang",
    address: {
      street: "707 Oak Blvd",
      city: "Tampa",
      state: "FL",
      zipCode: "33601",
    },
    contactNumber: "555-2222",
  },
  {
    customerId: 21,
    firstName: "Grace",
    lastName: "Morgan",
    address: {
      street: "808 Elm Dr",
      city: "Columbus",
      state: "OH",
      zipCode: "43201",
    },
    contactNumber: "555-2323",
  },
  {
    customerId: 22,
    firstName: "Lucas",
    lastName: "Lopez",
    address: {
      street: "909 Pine Rd",
      city: "San Antonio",
      state: "TX",
      zipCode: "78201",
    },
    contactNumber: "555-2424",
  },
  {
    customerId: 23,
    firstName: "Stella",
    lastName: "Barnes",
    address: {
      street: "101 Maple St",
      city: "Orlando",
      state: "FL",
      zipCode: "32801",
    },
    contactNumber: "555-2525",
  },
  {
    customerId: 24,
    firstName: "Nathan",
    lastName: "Nguyen",
    address: {
      street: "202 Cedar Ave",
      city: "Las Vegas",
      state: "NV",
      zipCode: "89101",
    },
    contactNumber: "555-2626",
  },
  {
    customerId: 25,
    firstName: "Aria",
    lastName: "Kim",
    address: {
      street: "303 Oak Ln",
      city: "Kansas City",
      state: "MO",
      zipCode: "64101",
    },
    contactNumber: "555-2727",
  },
]);
