db.Employee.insertMany([
  {
    employeeId: 1,
    firstName: "Charlie",
    lastName: "Green",
    address: {
      street: "123 Birch St",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    contactNumber: "555-0505",
    position: "Manager",
  },
  {
    employeeId: 2,
    firstName: "Diana",
    lastName: "Brown",
    address: {
      street: "456 Cedar Ln",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85003",
    },
    contactNumber: "555-0606",
    position: "Pharmacist",
  },
  {
    employeeId: 3,
    firstName: "Ethan",
    lastName: "Black",
    address: {
      street: "789 Willow Way",
      city: "Nashville",
      state: "TN",
      zipCode: "37209",
    },
    contactNumber: "555-0707",
    position: "Cashier",
  },
  {
    employeeId: 4,
    firstName: "Fiona",
    lastName: "Gray",
    address: {
      street: "321 Spruce Ave",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
    },
    contactNumber: "555-0808",
    position: "CPhT",
  },
  {
    employeeId: 5,
    firstName: "George",
    lastName: "Adams",
    address: {
      street: "654 Pine St",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    contactNumber: "555-0909",
    position: "Pharmacist",
  },
  {
    employeeId: 6,
    firstName: "Hannah",
    lastName: "Clark",
    address: {
      street: "987 Oak Blvd",
      city: "Boston",
      state: "MA",
      zipCode: "02101",
    },
    contactNumber: "555-1010",
    position: "Cashier",
  },
  {
    employeeId: 7,
    firstName: "Ian",
    lastName: "Davis",
    address: {
      street: "432 Elm St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
    },
    contactNumber: "555-1111",
    position: "Cashier",
  },
]);
