db.Orders.insertMany([
  {
    orderId: 1,
    customerId: 10,
    employeeId: 6,
    orderDate: new Date("2023-01-27"),
    orderDetails: [{ medicineId: 21, quantity: 2 }],
  },
  {
    orderId: 2,
    customerId: 12,
    employeeId: 3,
    orderDate: new Date("2023-02-10"),
    orderDetails: [{ medicineId: 1, quantity: 1 }],
  },
  {
    orderId: 3,
    customerId: 13,
    employeeId: 7,
    orderDate: new Date("2023-01-27"),
    orderDetails: [{ medicineId: 1, quantity: 2 }],
  },
  {
    orderId: 4,
    customerId: 14,
    employeeId: 3,
    orderDate: new Date("2023-02-10"),
    orderDetails: [{ medicineId: 1, quantity: 3 }],
  },
  {
    orderId: 5,
    customerId: 15,
    employeeId: 3,
    orderDate: new Date("2023-02-01"),
    orderDetails: [{ medicineId: 2, quantity: 4 }],
  },
  {
    orderId: 6,
    customerId: 16,
    employeeId: 6,
    orderDate: new Date("2023-02-17"),
    orderDetails: [{ medicineId: 3, quantity: 3 }],
  },
  {
    orderId: 7,
    customerId: 17,
    employeeId: 6,
    orderDate: new Date("2023-02-08"),
    orderDetails: [{ medicineId: 11, quantity: 5 }],
  },
  {
    orderId: 8,
    customerId: 18,
    employeeId: 6,
    orderDate: new Date("2023-02-18"),
    orderDetails: [{ medicineId: 30, quantity: 3 }],
  },
  {
    orderId: 9,
    customerId: 19,
    employeeId: 7,
    orderDate: new Date("2023-02-05"),
    orderDetails: [{ medicineId: 20, quantity: 3 }],
  },
  {
    orderId: 10,
    customerId: 20,
    employeeId: 7,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 21, quantity: 3 }],
  },

  {
    orderId: 11,
    customerId: 1,
    employeeId: 3,
    orderDate: new Date("2023-02-05"),
    orderDetails: [{ medicineId: 22, quantity: 6 }],
  },
  {
    orderId: 12,
    customerId: 2,
    employeeId: 3,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 23, quantity: 3 }],
  },
  {
    orderId: 13,
    customerId: 3,
    employeeId: 6,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 24, quantity: 5 }],
  },
  {
    orderId: 14,
    customerId: 4,
    employeeId: 6,
    orderDate: new Date("2023-02-15"),
    orderDetails: [{ medicineId: 25, quantity: 2 }],
  },
  {
    orderId: 15,
    customerId: 4,
    employeeId: 6,
    orderDate: new Date("2023-02-18"),
    orderDetails: [{ medicineId: 26, quantity: 1 }],
  },
  {
    orderId: 16,
    customerId: 5,
    employeeId: 7,
    orderDate: new Date("2023-02-28"),
    orderDetails: [{ medicineId: 27, quantity: 3 }],
  },
  {
    orderId: 17,
    customerId: 6,
    employeeId: 3,
    orderDate: new Date("2023-03-01"),
    orderDetails: [{ medicineId: 28, quantity: 7 }],
  },
  {
    orderId: 18,
    customerId: 7,
    employeeId: 7,
    orderDate: new Date("2023-03-02"),
    orderDetails: [{ medicineId: 32, quantity: 2 }],
  },
  {
    orderId: 19,
    customerId: 8,
    employeeId: 7,
    orderDate: new Date("2023-03-03"),
    orderDetails: [{ medicineId: 33, quantity: 3 }],
  },

  {
    orderId: 20,
    customerId: 1,
    employeeId: 3,
    orderDate: new Date("2023-03-05"),
    orderDetails: [
      { medicineId: 1, quantity: 2 },
      { medicineId: 2, quantity: 1 },
    ],
  },
  {
    orderId: 21,
    customerId: 2,
    employeeId: 6,
    orderDate: new Date("2023-03-10"),
    orderDetails: [
      { medicineId: 2, quantity: 1 },
      { medicineId: 4, quantity: 2 },
    ],
  },
  {
    orderId: 22,
    customerId: 3,
    employeeId: 7,
    orderDate: new Date("2023-03-11"),
    orderDetails: [
      { medicineId: 3, quantity: 1 },
      { medicineId: 4, quantity: 2 },
    ],
  },
  {
    orderId: 23,
    customerId: 4,
    employeeId: 3,
    orderDate: new Date("2023-03-20"),
    orderDetails: [
      { medicineId: 4, quantity: 5 },
      { medicineId: 2, quantity: 2 },
    ],
  },
  {
    orderId: 24,
    customerId: 4,
    employeeId: 6,
    orderDate: new Date("2023-03-23"),
    orderDetails: [
      { medicineId: 5, quantity: 2 },
      { medicineId: 4, quantity: 2 },
    ],
  },

  {
    orderId: 25,
    customerId: 5,
    employeeId: 7,
    orderDate: new Date("2023-03-25"),
    orderDetails: [
      { medicineId: 6, quantity: 3 },
      { medicineId: 4, quantity: 2 },
    ],
  },
  {
    orderId: 26,
    customerId: 6,
    employeeId: 3,
    orderDate: new Date("2023-03-30"),
    orderDetails: [
      { medicineId: 7, quantity: 4 },
      { medicineId: 8, quantity: 2 },
    ],
  },
  {
    orderId: 27,
    customerId: 7,
    employeeId: 6,
    orderDate: new Date("2023-04-01"),
    orderDetails: [
      { medicineId: 9, quantity: 2 },
      { medicineId: 10, quantity: 1 },
    ],
  },
  {
    orderId: 28,
    customerId: 8,
    employeeId: 7,
    orderDate: new Date("2023-04-05"),
    orderDetails: [
      { medicineId: 11, quantity: 3 },
      { medicineId: 12, quantity: 2 },
    ],
  },
  {
    orderId: 29,
    customerId: 9,
    employeeId: 3,
    orderDate: new Date("2023-04-10"),
    orderDetails: [
      { medicineId: 13, quantity: 1 },
      { medicineId: 14, quantity: 2 },
    ],
  },

  {
    orderId: 30,
    customerId: 10,
    employeeId: 6,
    orderDate: new Date("2023-04-15"),
    orderDetails: [
      { medicineId: 15, quantity: 2 },
      { medicineId: 16, quantity: 3 },
    ],
  },
  {
    orderId: 31,
    customerId: 11,
    employeeId: 7,
    orderDate: new Date("2023-04-20"),
    orderDetails: [
      { medicineId: 17, quantity: 2 },
      { medicineId: 18, quantity: 1 },
    ],
  },
  {
    orderId: 32,
    customerId: 12,
    employeeId: 3,
    orderDate: new Date("2023-04-25"),
    orderDetails: [
      { medicineId: 19, quantity: 4 },
      { medicineId: 20, quantity: 2 },
    ],
  },
  {
    orderId: 33,
    customerId: 13,
    employeeId: 6,
    orderDate: new Date("2023-05-01"),
    orderDetails: [
      { medicineId: 21, quantity: 3 },
      { medicineId: 22, quantity: 2 },
    ],
  },
  {
    orderId: 34,
    customerId: 14,
    employeeId: 7,
    orderDate: new Date("2023-05-05"),
    orderDetails: [
      { medicineId: 23, quantity: 2 },
      { medicineId: 24, quantity: 1 },
    ],
  },

  {
    orderId: 35,
    customerId: 15,
    employeeId: 3,
    orderDate: new Date("2023-05-10"),
    orderDetails: [
      { medicineId: 25, quantity: 3 },
      { medicineId: 26, quantity: 2 },
    ],
  },
  {
    orderId: 36,
    customerId: 16,
    employeeId: 6,
    orderDate: new Date("2023-05-15"),
    orderDetails: [
      { medicineId: 27, quantity: 2 },
      { medicineId: 28, quantity: 1 },
    ],
  },
  {
    orderId: 37,
    customerId: 17,
    employeeId: 7,
    orderDate: new Date("2023-05-20"),
    orderDetails: [
      { medicineId: 29, quantity: 4 },
      { medicineId: 30, quantity: 2 },
    ],
  },
  {
    orderId: 38,
    customerId: 18,
    employeeId: 3,
    orderDate: new Date("2023-05-25"),
    orderDetails: [
      { medicineId: 31, quantity: 3 },
      { medicineId: 32, quantity: 2 },
    ],
  },
  {
    orderId: 39,
    customerId: 19,
    employeeId: 6,
    orderDate: new Date("2023-06-01"),
    orderDetails: [
      { medicineId: 33, quantity: 2 },
      { medicineId: 34, quantity: 1 },
    ],
  },
  {
    orderId: 40,
    customerId: 20,
    employeeId: 7,
    orderDate: new Date("2023-06-05"),
    orderDetails: [
      { medicineId: 35, quantity: 3 },
      { medicineId: 36, quantity: 2 },
    ],
  },
  {
    orderId: 41,
    customerId: 1,
    employeeId: 3,
    orderDate: new Date("2023-06-10"),
    orderDetails: [
      { medicineId: 1, quantity: 5 },
      { medicineId: 2, quantity: 2 },
    ],
  },
  {
    orderId: 42,
    customerId: 2,
    employeeId: 6,
    orderDate: new Date("2023-06-15"),
    orderDetails: [
      { medicineId: 3, quantity: 2 },
      { medicineId: 4, quantity: 1 },
    ],
  },
  {
    orderId: 43,
    customerId: 3,
    employeeId: 7,
    orderDate: new Date("2023-06-20"),
    orderDetails: [
      { medicineId: 5, quantity: 4 },
      { medicineId: 6, quantity: 2 },
    ],
  },
  {
    orderId: 44,
    customerId: 4,
    employeeId: 3,
    orderDate: new Date("2023-06-25"),
    orderDetails: [
      { medicineId: 7, quantity: 3 },
      { medicineId: 8, quantity: 2 },
    ],
  },
  {
    orderId: 45,
    customerId: 5,
    employeeId: 6,
    orderDate: new Date("2023-07-01"),
    orderDetails: [
      { medicineId: 9, quantity: 5 },
      { medicineId: 10, quantity: 3 },
    ],
  },
  {
    orderId: 46,
    customerId: 6,
    employeeId: 3,
    orderDate: new Date("2023-07-05"),
    orderDetails: [
      { medicineId: 11, quantity: 4 },
      { medicineId: 12, quantity: 2 },
    ],
  },
  {
    orderId: 47,
    customerId: 7,
    employeeId: 6,
    orderDate: new Date("2023-07-10"),
    orderDetails: [
      { medicineId: 13, quantity: 3 },
      { medicineId: 14, quantity: 1 },
    ],
  },
  {
    orderId: 48,
    customerId: 8,
    employeeId: 7,
    orderDate: new Date("2023-07-15"),
    orderDetails: [
      { medicineId: 15, quantity: 6 },
      { medicineId: 16, quantity: 2 },
    ],
  },
  {
    orderId: 49,
    customerId: 9,
    employeeId: 3,
    orderDate: new Date("2023-07-20"),
    orderDetails: [
      { medicineId: 17, quantity: 2 },
      { medicineId: 18, quantity: 3 },
    ],
  },
  {
    orderId: 50,
    customerId: 10,
    employeeId: 6,
    orderDate: new Date("2023-07-25"),
    orderDetails: [
      { medicineId: 19, quantity: 4 },
      { medicineId: 20, quantity: 5 },
    ],
  },
  {
    orderId: 51,
    customerId: 11,
    employeeId: 7,
    orderDate: new Date("2023-07-30"),
    orderDetails: [
      { medicineId: 21, quantity: 3 },
      { medicineId: 22, quantity: 2 },
    ],
  },
  {
    orderId: 52,
    customerId: 12,
    employeeId: 3,
    orderDate: new Date("2023-08-01"),
    orderDetails: [
      { medicineId: 23, quantity: 5 },
      { medicineId: 24, quantity: 3 },
    ],
  },
  {
    orderId: 53,
    customerId: 13,
    employeeId: 6,
    orderDate: new Date("2023-08-05"),
    orderDetails: [
      { medicineId: 25, quantity: 2 },
      { medicineId: 26, quantity: 4 },
    ],
  },
  {
    orderId: 54,
    customerId: 14,
    employeeId: 7,
    orderDate: new Date("2023-08-10"),
    orderDetails: [
      { medicineId: 27, quantity: 3 },
      { medicineId: 28, quantity: 1 },
    ],
  },
]);
